---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-manager
  namespace: sman
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sman
  name: secret-manager-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "list", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-manager-binding
  namespace: sman
subjects:
- kind: ServiceAccount
  name: secret-manager
  namespace: sman
roleRef:
  kind: Role
  name: secret-manager-role
  apiGroup: rbac.authorization.k8s.io